version: "3.7"

networks:
    proxy:
        external: true

services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: php.${APP_NAME}
        ports:
            - "80:8000"
        restart: unless-stopped
        volumes:
            - .:/var/www
        networks:
            - proxy

#    mariadb:
#        container_name: mariadb
#        image: mariadb:10
#        restart: unless-stopped
#        ports:
#            - "3306:3306"
#        environment:
#            MYSQL_ROOT_PASSWORD: "Psswd#123"
#            MYSQL_ROOT_HOST: "%"
#            MYSQL_ALLOW_EMPTY_PASSWORD: 1
#        volumes:
#            - mariadb:/var/lib/mysql
#        networks:
#            - proxy
#        ulimits:
#            nproc: 65535
#            nofile:
#                soft: 26677
#                hard: 46677
#
#volumes:
#  mariadb:
